// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyqiyLsS1sHeOKJ_lV4ntsWKOc_m6q4Sk',
    appId: '1:388440462230:web:2ff6f48e11c2ca3ded43b7',
    messagingSenderId: '388440462230',
    projectId: 'yazan-app-9d6a6',
    authDomain: 'yazan-app-9d6a6.firebaseapp.com',
    storageBucket: 'yazan-app-9d6a6.firebasestorage.app',
    measurementId: 'G-0S3XELC4S0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuqez6Q5K-HPmxcp1fuRBzdVgevYE-g_I',
    appId: '1:388440462230:android:f0ac899942d1c18bed43b7',
    messagingSenderId: '388440462230',
    projectId: 'yazan-app-9d6a6',
    storageBucket: 'yazan-app-9d6a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0v9hjf2bMdY-uYlwaiUbWQhp3oIXbiM0',
    appId: '1:388440462230:ios:b97a0cec7c9bd310ed43b7',
    messagingSenderId: '388440462230',
    projectId: 'yazan-app-9d6a6',
    storageBucket: 'yazan-app-9d6a6.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0v9hjf2bMdY-uYlwaiUbWQhp3oIXbiM0',
    appId: '1:388440462230:ios:b97a0cec7c9bd310ed43b7',
    messagingSenderId: '388440462230',
    projectId: 'yazan-app-9d6a6',
    storageBucket: 'yazan-app-9d6a6.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyqiyLsS1sHeOKJ_lV4ntsWKOc_m6q4Sk',
    appId: '1:388440462230:web:2ff6f48e11c2ca3ded43b7',
    messagingSenderId: '388440462230',
    projectId: 'yazan-app-9d6a6',
    authDomain: 'yazan-app-9d6a6.firebaseapp.com',
    storageBucket: 'yazan-app-9d6a6.firebasestorage.app',
    measurementId: 'G-0S3XELC4S0',
  );
}
